version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  statsd:
    image: prom/statsd-exporter:v0.12.2
    expose:
      - 9125
    ports:
      - 9125:9125
    networks:
      - ratelimit-network

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - statsd
    networks:
      - ratelimit-network
    volumes:
      - ./examples/ratelimit/config:/data/ratelimit/config
    environment:
      - USE_STATSD=true
      - STATSD_HOST=statsd
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false

  envoy-proxy:
    image: envoyproxy/envoy:v1.14.4
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
#      - "--component-log-level pool:info,upstream:info,connection:info,config:debug,router:debug"
    volumes:
      - ./examples/envoy/proxy.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
       - "8888"
       - "8001"
    ports:
       - "8888:8888"
       - "8001:8001"

  envoy-mock:
    image: envoyproxy/envoy:v1.14.4
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
#      - "--component-log-level pool:info,upstream:info,connection:info,config:debug"
    volumes:
      - ./examples/envoy/mock.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
       - "9999"
    ports:
       - "9999:9999"

networks:
  ratelimit-network:
