version: "3"
services:

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  memcached:
    image: memcached:alpine
    expose:
      - 11211
    ports:
      - 11211:11211
    networks:
      - ratelimit-network

  # minimal container that builds the ratelimit service binary and exits.
  ratelimit-build:
    image: golang:1.14-alpine
    working_dir: /go/src/github.com/envoyproxy/ratelimit
    command: go build -o /usr/local/bin/ratelimit ./src/service_cmd/main.go
    volumes:
      - .:/go/src/github.com/envoyproxy/ratelimit
      - binary:/usr/local/bin/

  ratelimit-client-build:
    image: golang:1.14-alpine
    working_dir: /go/src/github.com/envoyproxy/ratelimit
    command: go build -o /usr/local/bin/ratelimit_client ./src/client_cmd/main.go
    volumes:
      - .:/go/src/github.com/envoyproxy/ratelimit
      - binary:/usr/local/bin/

  ratelimit:
    image: alpine:3.6
    command: >
        sh -c "until test -f /usr/local/bin/ratelimit; do sleep 5; done; /usr/local/bin/ratelimit"
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - ratelimit-build
      - ratelimit-client-build
    networks:
      - ratelimit-network
    volumes:
      - binary:/usr/local/bin/
      - ./examples:/data
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - MEMCACHE_HOST_PORT=memcached:11211

networks:
  ratelimit-network:

volumes:
  binary:
