---
domain: quota
descriptors:
  - key: service
    value: service_1
    quota_mode: true
    rate_limit:
      unit: minute
      requests_per_unit: 1
  - key: service
    value: service_2
    quota_mode: true
    rate_limit:
      unit: minute
      requests_per_unit: 2
